#!/usr/bin/env python3
"""
Generate coverage reports from gcov output with validation and multiple output formats.

Usage:
    generate_coverage_report.py [--format text|json] <source_files...>

Examples:
    generate_coverage_report.py pmic_core.c pmic_wdg.c
    generate_coverage_report.py --format json pmic_core.c pmic_wdg.c
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple


class CoverageReport:
    """Generate and format coverage reports from gcov data."""

    def __init__(self):
        self.files_data: List[Dict] = []
        self.total_lines = 0
        self.covered_lines = 0
        self.uncovered_lines = 0

    def validate_prerequisites(self) -> None:
        """Check that required tools are available."""
        if not shutil.which("llvm-cov-14"):
            print("ERROR: llvm-cov-14 not found in PATH!", file=sys.stderr)
            print("Please install: sudo apt-get install llvm-14", file=sys.stderr)
            sys.exit(1)

    def validate_gcda_files(self) -> None:
        """Check that .gcda files were generated by the test run."""
        gcda_files = list(Path(".").glob("*.gcda"))
        if not gcda_files:
            print("ERROR: No .gcda files found!", file=sys.stderr)
            print("Tests may not have run or coverage instrumentation may be missing.", file=sys.stderr)
            sys.exit(1)

    def generate_gcov(self, source_file: str) -> Path:
        """
        Run llvm-cov gcov on a source file to generate .gcov output.

        Args:
            source_file: Path to source file (e.g., "pmic_core.c")

        Returns:
            Path to generated .gcov file

        Raises:
            SystemExit: If gcov command fails
        """
        source_path = Path(source_file)
        source_name = source_path.stem  # Get filename without extension
        gcda_file = f"{source_name}.gcda"

        if not Path(gcda_file).exists():
            print(f"WARNING: {gcda_file} not found, skipping {source_file}", file=sys.stderr)
            return None

        try:
            # Run llvm-cov gcov on the .gcda file
            result = subprocess.run(
                ["llvm-cov-14", "gcov", "-o", ".", gcda_file],
                capture_output=True,
                text=True,
                check=True
            )
        except subprocess.CalledProcessError as e:
            print(f"ERROR: gcov failed for {source_file}", file=sys.stderr)
            print(f"Command output: {e.stderr}", file=sys.stderr)
            sys.exit(1)

        # Find the generated .gcov file
        gcov_file = Path(f"{source_name}.c.gcov")
        if not gcov_file.exists():
            # Try alternative naming
            gcov_file = Path(f"{source_path.name}.gcov")
            if not gcov_file.exists():
                print(f"ERROR: Expected .gcov file not found for {source_file}", file=sys.stderr)
                sys.exit(1)

        return gcov_file

    def parse_gcov_file(self, gcov_file: Path) -> Tuple[int, int, int]:
        """
        Parse a .gcov file to count covered and uncovered lines.
        Respects LCOV_EXCL_LINE markers in source code.

        Args:
            gcov_file: Path to .gcov file

        Returns:
            Tuple of (total_lines, covered_lines, uncovered_lines)
        """
        if not gcov_file:
            return (0, 0, 0)

        total = 0
        covered = 0
        uncovered = 0

        # Regex patterns for gcov output:
        # Executed lines: "    12:   42:  int x = 5;"
        # Unexecuted lines: "#####:   43:  return 0;"
        # Non-code lines: "    -:   44:  }"
        executed_pattern = re.compile(r'^\s+(\d+):\s+\d+:')
        unexecuted_pattern = re.compile(r'^\s+#####:\s+\d+:')

        # Pattern to detect LCOV exclusion markers in the code (both /* */ and // styles)
        excl_line_pattern = re.compile(r'(/\*\s*LCOV_EXCL_LINE|//\s*LCOV_EXCL_LINE)')
        excl_start_pattern = re.compile(r'(/\*\s*LCOV_EXCL_START|//\s*LCOV_EXCL_START)')
        excl_stop_pattern = re.compile(r'(/\*\s*LCOV_EXCL_STOP|//\s*LCOV_EXCL_STOP)')

        in_excl_block = False
        with gcov_file.open('r', encoding='utf-8', errors='ignore') as f:
            for line in f:
                # Check for exclusion block markers
                if excl_start_pattern.search(line):
                    in_excl_block = True
                if excl_stop_pattern.search(line):
                    in_excl_block = False
                    continue

                # Check if line has LCOV_EXCL_LINE marker or is in exclusion block
                if excl_line_pattern.search(line) or in_excl_block:
                    # Skip this line from coverage counting
                    continue

                if executed_pattern.match(line):
                    total += 1
                    covered += 1
                elif unexecuted_pattern.match(line):
                    total += 1
                    uncovered += 1

        return (total, covered, uncovered)

    def process_source_file(self, source_file: str) -> None:
        """Process a single source file and add to report data."""
        gcov_file = self.generate_gcov(source_file)
        total, covered, uncovered = self.parse_gcov_file(gcov_file)

        # Calculate coverage percentage
        coverage_percent = (covered / total * 100) if total > 0 else 0.0

        # Add to files data
        self.files_data.append({
            "name": Path(source_file).name,
            "total_lines": total,
            "covered_lines": covered,
            "uncovered_lines": uncovered,
            "coverage_percent": round(coverage_percent, 2)
        })

        # Update totals
        self.total_lines += total
        self.covered_lines += covered
        self.uncovered_lines += uncovered

    def generate_text_report(self) -> str:
        """Generate human-readable text report."""
        lines = []
        lines.append("")
        lines.append("=" * 80)
        lines.append("COVERAGE REPORT")
        lines.append("=" * 80)
        lines.append("")

        # Table header
        lines.append(f"{'File':<30} {'Total':>10} {'Covered':>10} {'Uncovered':>12} {'Coverage':>10}")
        lines.append("-" * 80)

        # Sort files by coverage percentage (lowest first to highlight gaps)
        sorted_files = sorted(self.files_data, key=lambda x: x['coverage_percent'])

        # File rows
        for file_data in sorted_files:
            name = file_data['name']
            total = file_data['total_lines']
            covered = file_data['covered_lines']
            uncovered = file_data['uncovered_lines']
            percent = file_data['coverage_percent']

            lines.append(f"{name:<30} {total:>10} {covered:>10} {uncovered:>12} {percent:>9.2f}%")

        # Summary row
        lines.append("-" * 80)
        total_percent = (self.covered_lines / self.total_lines * 100) if self.total_lines > 0 else 0.0
        lines.append(f"{'TOTAL':<30} {self.total_lines:>10} {self.covered_lines:>10} "
                     f"{self.uncovered_lines:>12} {total_percent:>9.2f}%")
        lines.append("=" * 80)
        lines.append("")

        return "\n".join(lines)

    def generate_json_report(self) -> str:
        """Generate machine-readable JSON report."""
        total_percent = (self.covered_lines / self.total_lines * 100) if self.total_lines > 0 else 0.0

        report = {
            "timestamp": datetime.now().isoformat(),
            "total_coverage": round(total_percent, 2),
            "total_lines": self.total_lines,
            "covered_lines": self.covered_lines,
            "uncovered_lines": self.uncovered_lines,
            "files": sorted(self.files_data, key=lambda x: x['name'])
        }

        return json.dumps(report, indent=2)

    def save_report(self, report_text: str, format_type: str) -> Path:
        """Save report to coverage/ directory."""
        output_dir = Path("coverage")
        output_dir.mkdir(exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        extension = "json" if format_type == "json" else "txt"
        output_file = output_dir / f"{timestamp}_coverage.{extension}"

        output_file.write_text(report_text)
        return output_file


def main():
    parser = argparse.ArgumentParser(
        description="Generate coverage reports from gcov output",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s pmic_core.c pmic_wdg.c
  %(prog)s --format json pmic_core.c pmic_wdg.c
        """
    )
    parser.add_argument(
        "--format",
        choices=["text", "json"],
        default="text",
        help="Output format (default: text)"
    )
    parser.add_argument(
        "source_files",
        nargs="+",
        help="Source files to generate coverage for"
    )

    args = parser.parse_args()

    # Create report generator
    report = CoverageReport()

    # Validate prerequisites
    report.validate_prerequisites()
    report.validate_gcda_files()

    # Process each source file
    for source_file in args.source_files:
        report.process_source_file(source_file)

    # Generate both text and JSON reports by default
    text_report = report.generate_text_report()
    json_report = report.generate_json_report()

    # Save both formats
    text_file = report.save_report(text_report, "text")
    json_file = report.save_report(json_report, "json")

    # Print text report to stdout (human-readable)
    print(text_report)

    # Print save locations to stderr
    print(f"\nReports saved:", file=sys.stderr)
    print(f"  Text: {text_file}", file=sys.stderr)
    print(f"  JSON: {json_file}", file=sys.stderr)


if __name__ == "__main__":
    main()
